# Generated by Django 5.1.3 on 2024-12-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='seating_capacity',
            field=models.IntegerField(choices=[(5, '5 Seats'), (6, '6 Seats'), (7, '7 Seats')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10),
        ),
    ]
