# Generated by Django 5.1.3 on 2024-12-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'car')},
        ),
    ]
