# Generated by Django 5.1.3 on 2024-12-12 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_car_available_from_car_available_to_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 20, 7, 725496), null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_to',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 20, 7, 725496), null=True),
        ),
    ]
