# Generated by Django 5.1.3 on 2024-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_car_available_from_alter_car_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='available_to',
            field=models.DateTimeField(null=True),
        ),
    ]
