# Generated by Django 5.1.3 on 2024-12-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_car_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingHistory',
        ),
    ]
