# Generated by Django 5.1.3 on 2024-12-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_bookinghistory_booking_delete_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
